/**
 * Bug Condition Exploration Property Test
 * 
 * Feature: cache-bool-test-fix
 * Bug: Test generator produces values that Cache.bool() treats as true
 * 
 * CRITICAL: This test MUST FAIL on unfixed code - failure confirms the bug exists
 * 
 * Purpose: Surface counterexamples that demonstrate the bug
 * - Generator produces "1" → Cache.bool("1") returns true → Bug confirmed
 * - Generator produces "TRUE", "True", etc. → Cache.bool() returns true → Bug confirmed
 * 
 * Expected Outcome: Test FAILS (this is correct - it proves the bug exists)
 * 
 * Validates: Requirements 1.1, 1.2, 1.3
 */

import { describe, it, expect } from '@jest/globals';
import fc from 'fast-check';
import { Cache } from '../../../../src/lib/dao-cache.js';

describe('Bug Condition Exploration - Test Generator Produces Truthy Values', () => {
  
  /**
   * Property 1: Bug Condition - Test Generator Produces Truthy Values
   * 
   * This test encodes the EXPECTED behavior: the generator should only produce
   * values that Cache.bool() treats as false.
   * 
   * On UNFIXED code: This test will FAIL because the current generator produces
   * "1" and case-insensitive "true" variations, which Cache.bool() treats as true.
   * 
   * On FIXED code: This test will PASS because the fixed generator excludes
   * truthy values.
   * 
   * Scoped PBT Approach: Test concrete failing cases: "1", "TRUE", "True", "TrUe"
   */
  it('Property 1: Generator should only produce values that Cache.bool() treats as false', () => {
    // Test the specific values that cause the bug
    const buggyValues = [
      '1',           // Cache.bool('1') returns true
      'TRUE',        // Cache.bool('TRUE') returns true (case-insensitive)
      'True',        // Cache.bool('True') returns true (case-insensitive)
      'TrUe',        // Cache.bool('TrUe') returns true (case-insensitive)
      'true',        // Cache.bool('true') returns true
      ' true ',      // Cache.bool(' true ') returns true (trimmed)
      ' 1 ',         // Cache.bool(' 1 ') returns true (trimmed)
      'tRuE'         // Cache.bool('tRuE') returns true (case-insensitive)
    ];
    
    // For each buggy value, verify that Cache.bool() treats it as true
    // This confirms these values should NOT be generated by the test generator
    buggyValues.forEach(value => {
      const result = Cache.bool(value);
      
      // EXPECTED: result should be true (confirming these are truthy values)
      // This assertion will PASS, proving these values are problematic
      expect(result).toBe(true);
    });
  });
  
  /**
   * Property 2: Current generator CAN produce truthy values (demonstrates the bug)
   * 
   * This test directly tests the problematic values that the current generator
   * ALLOWS through its filter: s !== 'true'
   * 
   * The bug is that the filter only excludes the exact string 'true', but allows:
   * - "1" (which Cache.bool treats as true)
   * - "TRUE", "True", "TrUe", etc. (case-insensitive variations)
   * 
   * EXPECTED OUTCOME: This test will FAIL because these values pass the current
   * filter but Cache.bool() treats them as true.
   * 
   * NOTE: This test is skipped after the fix is applied because it tests the OLD
   * filter behavior. After the fix, this test is no longer relevant.
   */
  it.skip('Property 2: Current generator CAN produce truthy values (demonstrates the bug)', () => {
    // The current filter from line 71: s !== 'true'
    const currentFilter = (s) => s !== 'true';
    
    // These values PASS the current filter (bug!)
    const valuesThatPassCurrentFilter = [
      '1',           // Passes filter: '1' !== 'true' → true
      'TRUE',        // Passes filter: 'TRUE' !== 'true' → true
      'True',        // Passes filter: 'True' !== 'true' → true
      'TrUe',        // Passes filter: 'TrUe' !== 'true' → true
      ' true ',      // Passes filter: ' true ' !== 'true' → true
      ' 1 '          // Passes filter: ' 1 ' !== 'true' → true
    ];
    
    // For each value that passes the filter, verify it's actually truthy
    // This demonstrates the bug: filter allows truthy values through
    valuesThatPassCurrentFilter.forEach(value => {
      // Step 1: Verify this value passes the current filter
      expect(currentFilter(value)).toBe(true);
      
      // Step 2: Verify Cache.bool() treats it as true (the bug!)
      const boolResult = Cache.bool(value);
      
      // This assertion FAILS for unfixed code, proving the bug exists
      // The generator allows values that Cache.bool() treats as true
      expect(boolResult).toBe(false);  // EXPECTED: false, ACTUAL: true (BUG!)
    });
  });
  
  /**
   * Property 3: Demonstrate specific bug cases
   * 
   * This test explicitly shows that the current generator's filter
   * (s !== 'true') does not exclude "1" or case-insensitive variations.
   * 
   * EXPECTED OUTCOME: All assertions PASS, confirming the bug exists
   */
  it('Property 3: Current filter allows truthy values to pass through', () => {
    // The current filter: s !== 'true'
    const currentFilter = (s) => s !== 'true';
    
    // Test that problematic values pass the current filter
    expect(currentFilter('1')).toBe(true);        // "1" passes filter but is truthy
    expect(currentFilter('TRUE')).toBe(true);     // "TRUE" passes filter but is truthy
    expect(currentFilter('True')).toBe(true);     // "True" passes filter but is truthy
    expect(currentFilter('TrUe')).toBe(true);     // "TrUe" passes filter but is truthy
    expect(currentFilter(' true ')).toBe(true);   // " true " passes filter but is truthy
    
    // Verify these values are actually truthy according to Cache.bool()
    expect(Cache.bool('1')).toBe(true);
    expect(Cache.bool('TRUE')).toBe(true);
    expect(Cache.bool('True')).toBe(true);
    expect(Cache.bool('TrUe')).toBe(true);
    expect(Cache.bool(' true ')).toBe(true);
    
    // This demonstrates the bug: the filter allows truthy values through
  });
  
  /**
   * Property 4: Document expected behavior for the fix
   * 
   * This test documents what the FIXED generator should do:
   * exclude both "1" and case-insensitive "true" variations.
   * 
   * EXPECTED OUTCOME: This test PASSES, showing what the fix should achieve
   */
  it('Property 4: Fixed filter should exclude all truthy values', () => {
    // The FIXED filter should be:
    const fixedFilter = (s) => {
      const normalized = s.trim().toLowerCase();
      return normalized !== 'true' && normalized !== '1';
    };
    
    // Test that problematic values are BLOCKED by the fixed filter
    expect(fixedFilter('1')).toBe(false);        // "1" blocked
    expect(fixedFilter('TRUE')).toBe(false);     // "TRUE" blocked
    expect(fixedFilter('True')).toBe(false);     // "True" blocked
    expect(fixedFilter('TrUe')).toBe(false);     // "TrUe" blocked
    expect(fixedFilter(' true ')).toBe(false);   // " true " blocked
    expect(fixedFilter(' 1 ')).toBe(false);      // " 1 " blocked
    
    // Test that valid falsy values still pass
    expect(fixedFilter('false')).toBe(true);     // "false" allowed
    expect(fixedFilter('0')).toBe(true);         // "0" allowed
    expect(fixedFilter('')).toBe(true);          // "" allowed
    expect(fixedFilter('no')).toBe(true);        // "no" allowed
    expect(fixedFilter('random')).toBe(true);    // other strings allowed
    
    // This shows the correct behavior for the fix
  });
});
